# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: EventPlanning_development
  username: postgres
  password: Satyendra@84%
  host: localhost
  port: 5432

test:
  <<: *default
  database: EventPlanning_test
  username: postgres
  password: Satyendra@84%
  host: localhost
  port: 5432

production:
  <<: *default
  database: EventPlanning_production
  username: postgres
  password: Satyendra@84%
  host: localhost
  port: 5432